namespace Service.Utilities
{
    public class SuccessErrorMessageInfo
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public bool IsContainerAutoGenerated { get; set; }


    }
}
